# Deploy documentation when push to main

name: Deploy docs

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install mkdocs
          python -m pip install mkdocs-material
          python -m pip install mkdocs-jupyter
          python -m pip install mkdocstrings[python]
          python -m pip install mkdocs-gen-files
          python -m pip install mkdocs-include-markdown-plugin
      - name: Deploy docs
        run: mkdocs gh-deploy --force
